version: 2.1

orbs:
  android: circleci/android@1.0.9

jobs:
  build:
    docker:
      - image: circleci/android:api-33-node
    environment:
      TERM: xterm
      ANDROID_SDK_ROOT: /sdk
    working_directory: ~/project
    steps:
      - checkout

      # Restore Gradle cache
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
            - gradle-cache-

      - run:
          name: Accept Android SDK licenses
          command: |
            yes | sdkmanager --licenses || true

      - run:
          name: Install Android SDK packages
          command: |
            sdkmanager "platform-tools" "platforms;android-36" "build-tools;33.0.2" "tools" || true

      - run:
          name: Make Gradle wrapper executable
          command: chmod +x ./gradlew

      - run:
          name: Run unit tests
          command: ./gradlew testDebugUnitTest --stacktrace --no-daemon

      - run:
          name: Assemble debug APK
          command: ./gradlew assembleDebug --stacktrace --no-daemon

      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apks

      - store_test_results:
          path: app/build/test-results

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

workflows:
  build_and_test:
    jobs:
      - build
