version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.08
    working_directory: ~/project
    environment:
      ANDROID_SDK_ROOT: /opt/android/sdk
    steps:
      - checkout

      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

      - run:
          name: Ensure gradlew is executable
          command: chmod +x ./gradlew

      - run:
          name: Print Java info (should be Java 17)
          command: java -version || true

      - run:
          name: Accept Android SDK licenses (if available)
          command: |
            if [ -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
              yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses || true
            elif command -v sdkmanager >/dev/null 2>&1; then
              yes | sdkmanager --licenses || true
            else
              echo "sdkmanager not found; skipping license accept"
            fi

      - run:
          name: Install Android SDK components (if needed)
          command: |
            if [ -x "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
              "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" "platform-tools" "platforms;android-36" "build-tools;33.0.2" || true
            elif command -v sdkmanager >/dev/null 2>&1; then
              sdkmanager "platform-tools" "platforms;android-36" "build-tools;33.0.2" || true
            else
              echo "sdkmanager not found; assuming image includes SDKs"
            fi

      - run:
          name: Download dependencies
          command: ./gradlew --no-daemon dependencies || true

      - run:
          name: Run Build (assemble)
          command: ./gradlew assembleDebug --stacktrace --no-daemon

      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: apks

      - run:
          name: Run unit tests
          command: ./gradlew testDebugUnitTest --stacktrace --no-daemon

      - store_test_results:
          path: app/build/test-results

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

workflows:
  build_and_test:
    jobs:
      - build